import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useMediaQuery from '@mui/material/useMediaQuery';

export default function Home() {
  const isDesktop = useMediaQuery('(min-width: 1080px)');
  return (
    <div className={styles.container}>
      <Head>
        <title>Jungle Maniacs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isDesktop ? <Image layout="fill" src="/images/coming-soon-desktop.jpg" alt="logo"  /> : <Image layout="fill" src="/images/coming-soon-mobile.jpg" alt="logo"  />}
      </main>
 
      
    </div>
  )
}
 